### ISSUE TITLE
what does mean "Invalid parameters(Currency not supported by Merchant Account)

### ISSUE THREAD

**Issue by nikuh** [myussufz/react-native-ipay88-sdk#5]
Hello

I'm integrating the ipay88 in my react-native project.
my option of the source code is as following

try {
        const data = {};
     
        data.paymentId = "2"; // refer to ipay88 docs
        data.merchantKey = "merchantKey";
        data.merchantCode ="merchantCode";
        data.referenceNo = "Tcee454656";
        data.amount = "1.00";
        data.currency = 'MYR';
        data.productDescription = "Payment for mobile";
        data.userName = "test";
        data.userEmail = "test@gmail.com";
        data.userContact = "0123456789";
        data.remark = "me";
        data.utfLang = "UTF-8";
        data.country = "MY";
        data.backendUrl = "http://haipsy33.test.com/";
      const errs = Pay(data);
        console.log(errs,'errrr');
        if (Object.keys(errs).length > 0) {
          console.log(errs,'yyy');
        }
      } catch (e) {
        console.log(e,'ttt');
      }

How account key and code was checked in web and it works fine on web site.

For now in mobile (ios and android) the response is as following.
"Invalid parameters(Currency not supported by Merchant Account)
![image](https://user-images.githubusercontent.com/16105192/49630849-cece5800-fa2a-11e8-9960-88c002500cee.png)

I don't know why this error is coming.

please help me

Best Regards

**Comment by ManigandanRaamanathan** [comment]
@nikuh Yo the currency should be MYR not RM. Follow international standard currency code

**Comment by ManigandanRaamanathan** [comment]
@nikuh  if it works, Let me know.

**Comment by nikuh** [comment]
Hello

Thank you for help.

I did used the "MYR" as currency code, but issues is same still.

Best Regards

**Comment by myussufz** [comment]
@nikuh you should get different key and code from ipay88. Thank you.
